/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package org.example;

//import com.fasterxml.jackson.core.JsonParseException; 
//import com.fasterxml.jackson.core; 
//import com.fasterxml.jackson.core.*; 
//import com.fasterxml.jackson.core.*; 
//import org.slf4j.*;
//import org.junit.Test;
//import org.junit.*;

public class App {
    /*
    public String getGreeting() {
        //return "Hello World!";
        return "Here is new app main!";
    }
    */
    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        System.out.println("Here is app!");
    }
}
