/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class App {
    /*
    public String getGreeting() {
        //return "Hello World!";
        return "Here is new app main!";
    }
    */
    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        System.out.println("Here is app!");
    }
}
